export function getMunicipalities(county: string | undefined): string[] {
  if (county === "agder") {
    return [
      "Arendal",
      "Birkenes",
      "Bygland",
      "Bykle",
      "Evje og Hornnes",
      "Farsund",
      "Flekkefjord",
      "Gjerstad",
      "Grimstad",
      "Iveland",
      "Kristiansand",
      "Lillesand",
      "Lindesnes",
      "Lyngdal",
      "Risør",
      "Songdalen",
      "Søgne",
      "Tvedestrand",
      "Valle",
      "Vegårshei",
      "Vennesla",
      "Åmli",
      "Åseral",
    ]
  }
  if (county === "akershus") {
    return [
      "Aurskog-Høland",
      "Bærum",
      "Eidsvoll",
      "Enebakk",
      "Fet",
      "Frogn",
      "Gjerdrum",
      "Hurdal",
      "Lørenskog",
      "Nannestad",
      "Nes",
      "Nesodden",
      "Nittedal",
      "Oppegård",
      "Rælingen",
      "Skedsmo",
      "Ski",
      "Sørum",
      "Ullensaker",
      "Vestby",
      "Ås",
    ]
  }
  if (county === "buskerud") {
    return [
      "Flesberg",
      "Flå",
      "Gol",
      "Hemsedal",
      "Hol",
      "Hole",
      "Kongsberg",
      "Krødsherad",
      "Lier",
      "Modum",
      "Nesbyen",
      "Nore og Uvdal",
      "Ringerike",
      "Rollag",
      "Sigdal",
      "Ål",
      "Øvre Eiker",
    ]
  }

  if (county === "finnmark") {
    return [
      "Alta",
      "Berlevåg",
      "Båtsfjord",
      "Deatnu - Tana",
      "Gamvik",
      "Guovdageaidnu - Kautokeino",
      "Hammerfest - Hámmerfeasta",
      "Hasvik",
      "Kárášjohka - Karasjok",
      "Lebesby",
      "Loppa",
      "Måsøy",
      "Nordkapp",
      "Porsanger - Porsáŋgu - Porsanki",
      "Sør-Varanger",
      "Unjárga - Nesseby",
      "Vadsø",
      "Vardø",
    ]
  }
  if (county === "innlandet") {
    return [
      "Alvdal",
      "Eidskog",
      "Elverum",
      "Engerdal",
      "Folldal",
      "Grue",
      "Hamar",
      "Kongsvinger",
      "Løten",
      "Nord-Odal",
      "Os",
      "Rendalen",
      "Ringsaker",
      "Stange",
      "Stor-Elvdal",
      "Sør-Odal",
      "Tolga",
      "Trysil",
      "Tynset",
      "Våler",
    ]
  }
  if (county === "møreogromsdal") {
    return [
      "Aure",
      "Averøy",
      "Fjord",
      "Giske",
      "Gjemnes",
      "Haram",
      "Hareid",
      "Herøy",
      "Hustadvika",
      "Kristiansund",
      "Molde",
      "Rauma",
      "Sande",
      "Smøla",
      "Stranda",
      "Sula",
      "Sunndal",
      "Surnadal",
      "Sykkylven",
      "Tingvoll",
      "Ulstein",
      "Vanylven",
      "Vestnes",
      "Volda",
      "Ålesund",
      "Ørsta",
    ]
  }
  if (county === "nordland") {
    return [
      "Alstahaug",
      "Andøy",
      "Ballangen",
      "Beiarn",
      "Bindal",
      "Bodø",
      "Brønnøy",
      "Bø",
      "Dønna",
      "Evenes",
      "Fauske",
      "Flakstad",
      "Gildeskål",
      "Grane",
      "Hadsel",
      "Hamarøy",
      "Hattfjelldal",
      "Hemnes",
      "Herøy",
      "Leirfjord",
      "Lurøy",
      "Lødingen",
      "Meløy",
      "Moskenes",
      "Narvik",
      "Nesna",
      "Rana",
      "Rødøy",
      "Røst",
      "Saltdal",
      "Sortland",
      "Steigen",
      "Sømna",
      "Sørfold",
      "Tjeldsund",
      "Træna",
      "Vagan",
      "Vefsn",
      "Vestvågøy",
      "Vevelstad",
      "Øksnes",
    ]
  }
  if (county === "oslo") {
    return ["Oslo"]
  }
  if (county === "rogaland") {
    return [
      "Bokn",
      "Eigersund",
      "Etne",
      "Finnøy",
      "Gjesdal",
      "Haugesund",
      "Hjelmeland",
      "Karmøy",
      "Kvitsøy",
      "Lund",
      "Randaberg",
      "Rennesøy",
      "Sandnes",
      "Sauda",
      "Sokndal",
      "Sola",
      "Stavanger",
      "Strand",
      "Suldal",
      "Time",
      "Tysvær",
      "Utsira",
      "Vindafjord",
    ]
  }
  if (county === "svalbard") {
    return ["Svalbard"]
  }
  if (county === "telemark") {
    return [
      "Bamble",
      "Drangedal",
      "Fyresdal",
      "Hjartdal",
      "Kragerø",
      "Kviteseid",
      "Nissedal",
      "Nome",
      "Notodden",
      "Porsgrunn",
      "Seljord",
      "Siljan",
      "Skien",
      "Tinn",
      "Tokke",
      "Vinje",
    ]
  }
  if (county === "troms") {
    return [
      "Balsfjord",
      "Bardu",
      "Berg",
      "Dyrøy",
      "Gratangen",
      "Harstad",
      "Ibestad",
      "Kvæfjord",
      "Kvænangen",
      "Lenvik",
      "Lyngen",
      "Målselv",
      "Salangen",
      "Senja",
      "Skjervøy",
      "Skånland",
      "Storfjord",
      "Torsken",
      "Tranøy",
      "Tromsø",
    ]
  }
  if (county === "trøndelag") {
    return [
      "Agdenes",
      "Bjugn",
      "Flatanger",
      "Fosnes",
      "Frosta",
      "Frøya",
      "Grong",
      "Hemne",
      "Hitra",
      "Holtålen",
      "Høylandet",
      "Inderøy",
      "Indre Fosen",
      "Levanger",
      "Lierne",
      "Malvik",
      "Meldal",
      "Melhus",
      "Meråker",
      "Midtre Gauldal",
      "Nærøy",
      "Oppdal",
      "Orkdal",
      "Osen",
      "Overhalla",
      "Rennebu",
      "Rindal",
      "Røros",
      "Selbu",
      "Skaun",
      "Snillfjord",
      "Steinkjer",
      "Stjørdal",
      "Trondheim",
      "Tydal",
      "Verdal",
      "Åfjord",
    ]
  }
  if (county === "vestfold") {
    return [
      "Andebu",
      "Hof",
      "Holmestrand",
      "Horten",
      "Lardal",
      "Larvik",
      "Nøtterøy",
      "Re",
      "Sandefjord",
      "Stokke",
      "Svelvik",
      "Tjøme",
      "Tønsberg",
    ]
  }
  if (county === "vestland") {
    return [
      "Askøy",
      "Aurland",
      "Austevoll",
      "Austrheim",
      "Bergen",
      "Bjørnafjorden",
      "Bremanger",
      "Eidfjord",
      "Etne",
      "Fedje",
      "Fitjar",
      "Fjaler",
      "Fusa",
      "Granvin",
      "Jondal",
      "Kinn",
      "Kvam",
      "Kvinnherad",
      "Luster",
      "Masfjorden",
      "Modalen",
    ]
  }
  if (county === "østfold") {
    return [
      "Aremark",
      "Askim",
      "Eidsberg",
      "Fredrikstad",
      "Halden",
      "Hobøl",
      "Hvaler",
      "Marker",
      "Moss",
      "Rakkestad",
      "Rygge",
      "Rømskog",
      "Råde",
      "Sarpsborg",
      "Skiptvet",
      "Spydeberg",
      "Trøgstad",
      "Våler",
    ]
  }
  return []
}
