import "@digdir/designsystemet-theme"
import "@digdir/designsystemet-css"
import "@/app/ui/global.css"
import Header from "@/app/ui/header/header"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  )
}
